-- MySQL Script generated by MySQL Workbench
-- Sun Feb 27 11:13:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ornamentacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ornamentacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ornamentacion` DEFAULT CHARACTER SET utf8 ;
USE `ornamentacion` ;

-- -----------------------------------------------------
-- Table `ornamentacion`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ornamentacion`.`Usuario` (
  `idUsuario` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `documento` BIGINT(10) NOT NULL,
  `nombre` VARCHAR(245) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(9) NOT NULL,
  `roll` ENUM('administrador ', 'vendedor') NOT NULL,
  `usuario` VARCHAR(145) NOT NULL,
  `contrasena` VARCHAR(240) NOT NULL,
  `estado` ENUM("Activo", "Inactivo") NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ornamentacion`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ornamentacion`.`Factura` (
  `idFactura` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numeroFactura` INT NOT NULL,
  `nombreCliente` VARCHAR(85) NOT NULL,
  `usuarioVendedor` BIGINT(10) UNSIGNED NOT NULL,
  `fecha` DATE NOT NULL,
  `valor` BIGINT(80) NOT NULL,
  `estado` ENUM("Proceso", "Finalizada", "Anulada") NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Usuario1_idx` (`usuarioVendedor` ASC) ,
  CONSTRAINT `fk_Factura_Usuario1`
    FOREIGN KEY (`usuarioVendedor`)
    REFERENCES `ornamentacion`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ornamentacion`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ornamentacion`.`Producto` (
  `idProducto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` ENUM("Fabricacion", "Instalacion", "Producto") NOT NULL,
  `nombre` VARCHAR(245) NOT NULL,
  `stock` INT NOT NULL,
  `valor` BIGINT(80) NOT NULL,
  `estado` ENUM("Activo", "Inactivo") NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ornamentacion`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ornamentacion`.`Proveedor` (
  `idProveedor` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `documento` BIGINT(10) NOT NULL,
  `nombre` VARCHAR(245) NOT NULL,
  `ciudad` VARCHAR(245) NOT NULL,
  `estado` ENUM("Activo", "Inactivo") NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ornamentacion`.`MateriaPrima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ornamentacion`.`MateriaPrima` (
  `idMateria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` ENUM("Varilla", "Perfiles", "Marco", "Divisiones", "Angulo", "Pintura", "Anticorrosivo", "Lija") NOT NULL,
  `stock` INT NOT NULL,
  `estado` ENUM("Activo", "Inactivo") NOT NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ornamentacion`.`detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ornamentacion`.`detalle_ventas` (
  `idOrdenCompra` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ventas_id` INT UNSIGNED NOT NULL,
  `Producto_IdProducto` INT UNSIGNED NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` INT NOT NULL,
  PRIMARY KEY (`idOrdenCompra`),
  INDEX `fk_OrdenCompra_Factura1_idx` (`ventas_id` ASC) ,
  INDEX `fk_OrdenCompra_Producto1_idx` (`Producto_IdProducto` ASC) ,
  CONSTRAINT `fk_OrdenCompra_Factura1`
    FOREIGN KEY (`ventas_id`)
    REFERENCES `ornamentacion`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdenCompra_Producto1`
    FOREIGN KEY (`Producto_IdProducto`)
    REFERENCES `ornamentacion`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ornamentacion`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ornamentacion`.`Pedidos` (
  `idPedidos` TINYINT(3) ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `numeroPedido` INT NOT NULL,
  `nombre` VARCHAR(245) NOT NULL,
  `fechaPedido` DATE NOT NULL,
  `fechaEntrega` DATE NOT NULL,
  `estado` ENUM("Activo", "Inactivo") NOT NULL,
  `Proveedor_IdProveedor` BIGINT(10) UNSIGNED NOT NULL,
  `Usuario_IdUsuario` BIGINT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idPedidos`),
  INDEX `fk_Pedidos_Proveedor1_idx` (`Proveedor_IdProveedor` ASC) ,
  INDEX `fk_Pedidos_Usuario1_idx` (`Usuario_IdUsuario` ASC) ,
  CONSTRAINT `fk_Pedidos_Proveedor1`
    FOREIGN KEY (`Proveedor_IdProveedor`)
    REFERENCES `ornamentacion`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Usuario1`
    FOREIGN KEY (`Usuario_IdUsuario`)
    REFERENCES `ornamentacion`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ornamentacion`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ornamentacion`.`DetallePedido` (
  `idDetallePedido` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `numeroDetallePedido` INT NOT NULL,
  `valor` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` ENUM("Activo", "Inactivo") NOT NULL,
  `pedidosId` TINYINT(3) ZEROFILL UNSIGNED NOT NULL,
  `materiaPrimaId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idDetallePedido`),
  INDEX `fk_DetallePedido_Pedidos1_idx` (`pedidosId` ASC) ,
  INDEX `fk_DetallePedido_MateriaPrima1_idx` (`materiaPrimaId` ASC) ,
  CONSTRAINT `fk_DetallePedido_Pedidos1`
    FOREIGN KEY (`pedidosId`)
    REFERENCES `ornamentacion`.`Pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallePedido_MateriaPrima1`
    FOREIGN KEY (`materiaPrimaId`)
    REFERENCES `ornamentacion`.`MateriaPrima` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ornamentacion`.`detalle_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ornamentacion`.`detalle_materia` (
  `idDetalle` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `detalle_materiacol` VARCHAR(45) NOT NULL,
  `MateriaPrima_idMateria` INT UNSIGNED NOT NULL,
  `Producto_IdProducto` INT UNSIGNED NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idDetalle`),
  INDEX `fk_detalle_materia_MateriaPrima1_idx` (`MateriaPrima_idMateria` ASC) ,
  INDEX `fk_detalle_materia_Producto1_idx` (`Producto_IdProducto` ASC) ,
  CONSTRAINT `fk_detalle_materia_MateriaPrima1`
    FOREIGN KEY (`MateriaPrima_idMateria`)
    REFERENCES `ornamentacion`.`MateriaPrima` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_materia_Producto1`
    FOREIGN KEY (`Producto_IdProducto`)
    REFERENCES `ornamentacion`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
